#file: noinspection undefined
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/news_springboot
    username: root
    password: 8082
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

jwt:
  SECRET_KEY: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

cloudinary:
  cloud-name: dvda6cmt8
  api-key: 235853855945823
  api-secret: NHlRYDpBxTUzFHumTgNpU5bv0es